### ISSUE TITLE
Investigate error for my tokens list

### ISSUE THREAD

**Issue by valera-rozuvan** [windingtree/stays-eth-barca#53]
The dapp shows same error that was on Thursday (16.06.2022) at launch when trying to browse My tokens list.

**Comment by valera-rozuvan** [comment]
This is the URL: https://win.so/token?tokenId=2

This is the error we see:

![image](https://user-images.githubusercontent.com/2273090/174559417-c057cacd-bbc3-4500-9a25-90187f6f8c77.png)

**Comment by kostysh** [comment]
There are no bookings at the moment, that is why this error occurs. #2 is non-existent token

**Comment by kostysh** [comment]
fixed by https://github.com/windingtree/stays-eth-barca/pull/55

**Comment by kostysh** [comment]
the long nonsense error message to: `Unable to get token #<tokenId>`
