### ISSUE TITLE
re-direct win.barcelona to win.so

### ISSUE THREAD

**Issue by lucarioams** [windingtree/stays-eth-barca#65]

**Comment by valera-rozuvan** [comment]
The redirect has been configured. It might take up to 24 hours to take effect, since this is on the DNS side. DNS changes sometimes take some time to propagate worldwide.

**Comment by valera-rozuvan** [comment]
https://win.barcelona/ now redirects to https://win.so/ 🔥

**Comment by lucarioams** [comment]
@valera-rozuvan this is not working for me, still

**Comment by lucarioams** [comment]
@valera-rozuvan I have tried it but still doesn't work for me..
![IMG_2AA0640AE282-1](https://user-images.githubusercontent.com/80516439/175101975-a4fe0c7a-1fc0-4eb3-82c7-b79f474f2e8b.jpeg)
.
