### ISSUE TITLE
Facility Management Page

### ISSUE THREAD

**Issue by lucarioams** [windingtree/stays-eth-barca#7]
### Component

Accommodation Providers

### Describe the feature you would like

currently called Lodging Facilities, we do not need to make a new UI/UX for it as it still will be mostly managed by us, however, if we have time we could make some minor improvements at least for ETHcc.

### Additional context

According to the screen recording of the process on the current test.win.so there is no way to configure date availability for a space.
see the recording
[screen recording](https://drive.google.com/file/d/1zb4nWyZojQkc-ztGDvSOi48GuoBiNKjx/view?usp=sharing)

**Comment by valera-rozuvan** [comment]
Discussed with @lucarioams - we are going to close this issue. Reason being that this page is not end-user facing. We are managing the facilities for now ourselves. So, to move on faster to Paris site, we will not allocate resources.

For next version of stays (Videre version) - we will redo the whole page.
