### ISSUE TITLE
Improving clarity of no rooms found page

### ISSUE THREAD

**Issue by lucarioams** [windingtree/stays-eth-barca#73]
### Describe the bug

When a traveller selects dates and no rooms are found we need to add to the text the following:

No Rooms Found, this could be due to a few reasons:
1 - There are no rooms for this period, try different dates
2 - Clear you cookies and cache and try again (see [how?)](https://support.google.com/accounts/answer/32050?hl=en&co=GENIE.Platform%3DDesktop)
<img width="1114" alt="noroomsfound" src="https://user-images.githubusercontent.com/80516439/174756122-7ee857fc-d526-4f24-b322-d6f1b445dd54.png">

**Comment by valera-rozuvan** [comment]
Fixed.
