### ISSUE TITLE
Spaces not showing 3-8 July

### ISSUE THREAD

**Issue by vsomsen** [windingtree/stays-eth-barca#77]
### Operating System

macOS (amd)

### What browsers are you seeing the problem on?

Chrome

### Describe the bug

For BCN, we have "CoImpact Coliving" that has availability 3-8 July (5 nights min. stay). But their spaces don't show to book. They have 2 dorm beds (spaces) that are both available. They uploaded themselves with their own wallet.

**Comment by valera-rozuvan** [comment]
![image](https://user-images.githubusercontent.com/2273090/175019655-d696e23d-4e64-4b9b-ac61-2b612c94be99.png)

https://win.so/search?startDay=132&numberOfDays=5&roomsNumber=1
