### ISSUE TITLE
Booking confirmation page

### ISSUE THREAD

**Issue by lucarioams** [windingtree/stays-eth-barca#8]
### Component

Travellers

### Describe the feature you would like

this confirmation page comes right after the booking went successfully (or gets denied).

> if possible it would already show the token id and view qr code button 

### Additional context
https://www.figma.com/file/gTcwOWZMxGxR5D3emBTMKG/win.so-bcn-x-paris?node-id=2210%3A7528

**Comment by valera-rozuvan** [comment]
Issue resolved.
